### ISSUE TITLE
Display recipies

### ISSUE THREAD

**Issue by JoshuaD9907** [JoshuaD9907/Recitation-012-Team-8#1]
Display all recipes in a scrollable window

**Comment by beaucave** [comment]
UAC: I should be able to clearly view a good amount (or all) recipes within the recipe data

**Comment by beaucave** [comment]
As a user, I should be able to easily view various recipes at a glance without being overwhelmed. 

UAC: Should be able to clearly view all (or at least, a good amount) of the recipes within the database. Should be easy to read/access.
